# 1  Recurrent Neural Network

In this part, you need to build the RNN unit in the diagram using only numpy .
Then you need to build the input to test RNN for no less than 4 time steps

In [2]:
import numpy as np

## 1.1 Tanh activation: forward

Implement the forward pass for the Tanh activation function in the `tanh_forward` function and test your implementation using the following:

In [13]:
def tanh_forward(x):
    out = (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))
    return out

In [14]:
# Test the tanh_forward function

x = np.linspace(-0.5, 0.5, num=12).reshape(3, 4)

out= tanh_forward(x)
correct_out = np.array([[-0.46211716, -0.38770051, -0.30786199, -0.22343882],
                        [-0.13552465, -0.04542327,  0.04542327,  0.13552465],
                        [ 0.22343882,  0.30786199,  0.38770051,  0.46211716]])

# Compare your output with ours. The error should be on the order of e-8
print('Testing tanh_forward function:')
print('difference: ', (out - correct_out))

Testing tanh_forward function:
difference:  [[ 2.73999023e-09  1.33874611e-09  2.58224614e-09 -2.81432277e-09]
 [ 2.92331293e-09  3.47872175e-09 -3.47872175e-09 -2.92331293e-09]
 [ 2.81432277e-09 -2.58224614e-09 -1.33874611e-09 -2.73999023e-09]]


## 1.2 Softmax activation: forward

Implement the forward pass for the softmax activation function in the `softmax_forward` function and test your implementation using the following:

In [28]:
def softmax_forward(x):
    e_x = np.exp(x - np.max(x)) # 减去最大值，防止溢出
    out = e_x / np.sum(e_x, axis=0)
    return out

In [31]:
# Test the softmax_forward function

x = np.linspace(-0.5, 0.5, num=12).reshape(3, 4)

out= softmax_forward(x)
correct_out = np.array([[0.22182884 ,0.22182884 ,0.22182884 ,0.22182884],
                        [0.31911211 ,0.31911211 ,0.31911211 ,0.31911211],
                        [0.45905905 ,0.45905905 ,0.45905905 ,0.45905905]])

# Compare your output with ours. The error should be on the order of e-8
print('Testing softmax_forward function:')
print('difference: ', (out - correct_out))

Testing softmax_forward function:
difference:  [[ 4.91230565e-09  4.91230562e-09  4.91230562e-09  4.91230562e-09]
 [-1.19795263e-09 -1.19795263e-09 -1.19795263e-09 -1.19795263e-09]
 [-3.71435299e-09 -3.71435299e-09 -3.71435299e-09 -3.71435299e-09]]


## 1.3 Building a single RNN cell according to instructions

And you need to test your cell according to the given input

In [32]:
# GRADED FUNCTION: rnn_cell_forward

def rnn_cell_forward(xt, a_prev, parameters):
    """
    Implements a single forward step of the RNN-cell as described in Figure (2)

    Arguments:
    xt -- your input data at timestep "t", numpy array of shape (n_x, m).
    a_prev -- Hidden state at timestep "t-1", numpy array of shape (n_a, m)
    parameters -- python dictionary containing:
                        Wax -- Weight matrix multiplying the input, numpy array of shape (n_a, n_x)
                        Waa -- Weight matrix multiplying the hidden state, numpy array of shape (n_a, n_a)
                        Wya -- Weight matrix relating the hidden-state to the output, numpy array of shape (n_y, n_a)
                        ba --  Bias, numpy array of shape (n_a, 1)
                        by -- Bias relating the hidden-state to the output, numpy array of shape (n_y, 1)
    Returns:
    a_next -- next hidden state, of shape (n_a, m)
    yt_pred -- prediction at timestep "t", numpy array of shape (n_y, m)
    cache -- tuple of values needed for the backward pass, contains (a_next, a_prev, xt, parameters)
    """
    
    # Retrieve parameters from "parameters"
    Waa, Wax, Wya, ba, by = parameters['Waa'], parameters['Wax'], parameters['Wya'], parameters['ba'], parameters['by']
    
    # Compute the hidden state with tanh activation and using your new hidden state a_next compute the prediction yt_pred
    W_aa_a_prev, W_ax_xt  = np.dot(Waa, a_prev), np.dot(Wax, xt)
    a_next = tanh_forward(W_aa_a_prev + W_ax_xt + ba)
    yt_pred = softmax_forward(np.dot(Wya, a_next) + by)
    # store values you need for backward propagation in cache
    cache = (a_next, a_prev, xt, parameters)
    
    return a_next, yt_pred, cache


In [34]:
# Testing your function
xt = np.linspace(-1, 1, num=30).reshape(3, 10)
a_prev = np.linspace(-1, 1, num=50).reshape(5, 10)
Waa = np.linspace(-1, 1, num=25).reshape(5, 5)
Wax = np.linspace(-1, 1, num=15).reshape(5, 3)
Wya = np.linspace(-1, 1, num=10).reshape(2, 5)
ba = np.linspace(-1, 1, num=5).reshape(5, 1)
by = np.linspace(-1, 1, num=2).reshape(2, 1)
parameters = {"Waa": Waa, "Wax": Wax, "Wya": Wya, "ba": ba, "by": by}
a_next, yt_pred, cache = rnn_cell_forward(xt, a_prev, parameters)

correct_yt_pred= np.array([[0.01173649, 0.00919828, 0.00893178, 0.01089865, 0.01526617, 0.02177653,
                            0.02945747, 0.03722571, 0.04439407, 0.05064493],
                            [0.98826351, 0.99080172, 0.99106822, 0.98910135, 0.98473383, 0.97822347,
                            0.97054253, 0.96277429, 0.95560593, 0.94935507]])
# Compare your output with ours. The error should be on the order of e-8
print('Testing rnn cell:')
print('difference: ', (yt_pred - correct_yt_pred))


Testing rnn cell:
difference:  [[ 3.46237604e-09  4.11825871e-09 -3.30776050e-09  9.71139542e-10
   9.37157874e-10 -2.67774309e-09  3.30873294e-09  4.75652538e-09
   3.97501351e-09  3.96566117e-09]
 [-3.46237605e-09 -4.11825862e-09  3.30776051e-09 -9.71139502e-10
  -9.37157907e-10  2.67774314e-09 -3.30873295e-09 -4.75652551e-09
  -3.97501354e-09 -3.96566113e-09]]


## 1.4 Follow the instructions to construct a RNN network

And you need to test your network according to the given input

In [35]:
# GRADED FUNCTION: rnn_forward

def rnn_forward(x, a0, parameters):
    """
    Implement the forward propagation of the recurrent neural network.

    Arguments:
    x -- Input data for every time-step, of shape (n_x, m, T_x).
    a0 -- Initial hidden state, of shape (n_a, m)
    parameters -- python dictionary containing:
                        Waa -- Weight matrix multiplying the hidden state, numpy array of shape (n_a, n_a)
                        Wax -- Weight matrix multiplying the input, numpy array of shape (n_a, n_x)
                        Wya -- Weight matrix relating the hidden-state to the output, numpy array of shape (n_y, n_a)
                        ba --  Bias numpy array of shape (n_a, 1)
                        by -- Bias relating the hidden-state to the output, numpy array of shape (n_y, 1)

    Returns:
    a -- Hidden states for every time-step, numpy array of shape (n_a, m, T_x)
    y_pred -- Predictions for every time-step, numpy array of shape (n_y, m, T_x)
    caches -- tuple of values needed for the backward pass, contains (list of caches, x)
    """
    
    # Initialize "caches" which contain the list of all cache
    caches = []
    
    # Retrieve dimensions from shapes of x and parameters["Wya"]
    n_x, m, T_x = x.shape
    n_y, n_a = parameters["Wya"].shape
    
    # initialize "a" and "y" with zeros
    a, y_pred = np.zeros((n_a, m, T_x)), np.zeros((n_y, m, T_x))
    
    # Initialize a_next
    a_next = a0
    
    # loop over all time-steps
    for t in range(T_x):
    
        # Update next hidden state, compute the prediction, get the cache
        a_next, yt_pred, cache = rnn_cell_forward(x[:, :, t], a_next, parameters)
    
        # Save the value of the new "next" hidden state in a
        a[:, :, t] = a_next
    
        # Save the value of the prediction in y
        y_pred[:, :, t] = yt_pred
    
        # Append "cache" to caches
        caches.append(cache)
    
    # store values needed for backward propagation in cache
    caches = (caches, x)
    
    return a, y_pred, caches


In [38]:
xt = np.linspace(-1, 1, num=120).reshape(3, 10,4)
a0 = np.linspace(-1, 1, num=50).reshape(5, 10)
Waa = np.linspace(-1, 1, num=25).reshape(5, 5)
Wax = np.linspace(-1, 1, num=15).reshape(5, 3)
Wya = np.linspace(-1, 1, num=10).reshape(2, 5)
ba = np.linspace(-1, 1, num=5).reshape(5, 1)
by = np.linspace(-1, 1, num=2).reshape(2, 1)
parameters = {"Waa": Waa, "Wax": Wax, "Wya": Wya, "ba": ba, "by": by}

a, y_pred, caches = rnn_forward(xt, a0, parameters)

correct_y_pred_1r3c = np.array([0.98938177, 0.92781377, 0.98516102, 0.94756773])
correct_a_4r1c = np.array([0.2609307,  0.98545286, 0.84171072, 0.99476474])
correct_caches_113 = np.array([-0.12605042, -0.1092437,  -0.09243697, -0.07563025])

# Compare your output with ours. The error should be on the order of e-8
print('Testing rnn network:')

print('y_difference: ', (y_pred[1][3] - correct_y_pred_1r3c))
print('a_difference: ', (a[4][1] - correct_a_4r1c))
print('cache_difference: ', (caches[1][1][3] - correct_caches_113))

Testing rnn network:
y_difference:  [ 9.11572484e-10 -4.37519909e-09  5.64888136e-10  3.66363306e-09]
a_difference:  [-3.13617465e-10 -2.13382212e-09  8.34690983e-10 -2.64970512e-09]
cache_difference:  [-1.68067227e-10  2.52100835e-09 -4.78991598e-09 -2.10084040e-09]


# 2  Backpropagation in recurrent neural networks

In modern deep learning frameworks, you only have to implement the forward pass, and the framework takes care of the backward pass, so most deep learning engineers do not need to bother with the details of the backward pass. If however you are an expert in calculus and want to see the details of backprop in RNNs, you can work through this optional portion of the notebook.

## 2.1 - Basic RNN backward pass

We will start by computing the backward pass for the basic RNN-cell.

### Deriving the one step backward functions:

To compute the rnn_cell_backward you need to compute the reference image in the homework. It is a good exercise to derive them by hand.

In [89]:
def rnn_cell_backward(da_next, cache):
    """
    Implements the backward pass for the RNN-cell (single time-step).
    Arguments:
    da_next -- Gradient of loss with respect to next hidden state
    cache -- python dictionary containing useful values (output of rnn_cell_forward())
    Returns:
    gradients -- python dictionary containing:
                        dx -- Gradients of input data, of shape (n_x, m)
                        da_prev -- Gradients of previous hidden state, of shape (n_a, m)
                        dWax -- Gradients of input-to-hidden weights, of shape (n_a, n_x)
                        dWaa -- Gradients of hidden-to-hidden weights, of shape (n_a, n_a)
                        dba -- Gradients of bias vector, of shape (n_a, 1)
    """
    
    # Retrieve values from cache
    a_next, a_prev, xt, parameters = cache
    
    # Retrieve values from parameters
    Waa, Wax, _, _, _ = parameters['Waa'], parameters['Wax'], parameters['Wya'], parameters['ba'], parameters['by']
 
    ### START CODE HERE ###
    
    # compute the gradient of tanh with respect to a_next (≈1 line)
    dtanh = (1 - a_next**2) * da_next
    
    # compute the gradient of the loss with respect to Wax (≈2 lines)
    dxt = np.dot(Wax.T, dtanh)
    dWax = np.dot(dtanh, xt.T)
 
    # compute the gradient with respect to Waa (≈2 lines)
    da_prev = np.dot(Waa.T, dtanh)
    dWaa = np.dot(dtanh, a_prev.T)
 
    # compute the gradient with respect to b (≈1 line)
    dba = np.sum(dtanh, axis=1, keepdims=True)  # 按行求和
 
    ### END CODE HERE ###
    
    # Store the gradients in a python dictionary
    gradients = {"dxt": dxt, "da_prev": da_prev, "dWax": dWax, "dWaa": dWaa, "dba": dba}
    
    return gradients

### test the backward function

In [90]:
np.random.seed(1)
xt = np.random.randn(3,10)
a_prev = np.random.randn(5,10)
Wax = np.random.randn(5,3)
Waa = np.random.randn(5,5)
Wya = np.random.randn(2,5)
ba = np.random.randn(5,1)
by = np.random.randn(2,1)
parameters = {"Wax": Wax, "Waa": Waa, "Wya": Wya, "ba": ba, "by": by}

a_next, yt, cache = rnn_cell_forward(xt, a_prev, parameters)
correct_gra_xt_2 = [-0.02886535,  0.15285269, -0.24771553, -0.1538868,  -0.30123978,
                    0.43068929,   0.1448896,   0.07010807, -0.22645813,  0.09275214]
da_next = np.random.randn(5,10)
gradients = rnn_cell_backward(da_next, cache)
print(gradients['dxt'][2]-correct_gra_xt_2)

[-4.15389161e-09  3.65399597e-09  2.11909662e-09  1.62985550e-09
 -7.39439565e-10 -9.61219659e-10 -3.89284660e-10 -1.21954563e-09
 -2.13211884e-09  1.41260277e-09]


## 2.2 Backward pass through the RNN


Implement the rnn_backward function. Initialize the return variables with zeros first and then loop through all the time steps while calling the rnn_cell_backward at each time timestep, update the other variables accordingly.



In [85]:
def rnn_backward(da, caches):
    """
    Implement the backward pass for a RNN over an entire sequence of input data.
​
    Arguments:
    da -- Upstream gradients of all hidden states, of shape (n_a, m, T_x)
    caches -- tuple containing information from the forward pass (rnn_forward)
    Returns:
    gradients -- python dictionary containing:
                        dx -- Gradient w.r.t. the input data, numpy-array of shape (n_x, m, T_x)
                        da0 -- Gradient w.r.t the initial hidden state, numpy-array of shape (n_a, m)
                        dWax -- Gradient w.r.t the input's weight matrix, numpy-array of shape (n_a, n_x)
                        dWaa -- Gradient w.r.t the hidden state's weight matrix, numpy-arrayof shape (n_a, n_a)
                        dba -- Gradient w.r.t the bias, of shape (n_a, 1)
    """
        
    ### START CODE HERE ###
    
    # Retrieve values from the first cache (t=1) of caches (≈2 lines)
    # _caches, x = caches
    _caches, _ = caches
    # a1, a0, x1, parameters = _caches[0]
    _, _, x1, _ = _caches[0]
    # Retrieve dimensions from da's and x1's shapes (≈2 lines)
    n_a, m, T_x = da.shape
    n_x, m = x1.shape
    # initialize the gradients with the right sizes (≈6 lines)
    dx = np.zeros((n_x, m, T_x))
    da0 = np.zeros((n_a, m))
    dWax = np.zeros((n_a, n_x))
    dWaa = np.zeros((n_a, n_a))
    dba = np.zeros((n_a, 1))
    da_prev = np.zeros((n_a, m))
    # Loop through all the time steps
    for t in reversed(range(T_x)):
        # Compute gradients at time step t. Choose wisely the "da_next" and the "cache" to use in the backward propagation step. (≈1 line)
        gradients = rnn_cell_backward(da[:, :, t] + da_prev, _caches[t])    # 计算每一个时间步的梯度

        # Retrieve derivatives from gradients (≈ 1 line)
        dxt, da_prevt, dWaxt, dWaat, dbat = gradients["dxt"], gradients["da_prev"], gradients["dWax"], gradients["dWaa"], gradients["dba"]
        
        # Increment global derivatives w.r.t parameters by adding their derivative at time-step t (≈4 lines)
        dx[:, :, t] = dxt
        dWax += dWaxt
        dWaa += dWaat
        dba += dbat
        
    # Set da0 to the gradient of a which has been backpropagated through all time-steps (≈1 line) 
    da0 = da_prevt
    
    ### END CODE HERE ###
    # Store the gradients in a python dictionary
    gradients = {"dx":dx, "da0":da0, "dWax":dWax, "dWaa":dWaa, "dba":dba}
    
    return gradients

### test the function 

In [88]:
np.random.seed(1)
x = np.random.randn(3,10,4)
a0 = np.random.randn(5,10)
Wax = np.random.randn(5,3)
Waa = np.random.randn(5,5)
Wya = np.random.randn(2,5)
ba = np.random.randn(5,1)
by = np.random.randn(2,1)
parameters = {"Wax": Wax, "Waa": Waa, "Wya": Wya, "ba": ba, "by": by}
a, y, caches = rnn_forward(x, a0, parameters)
da = np.random.randn(5, 10, 4)
gradients = rnn_backward(da, caches)

print("gradients[\"dx\"][1][2] =", gradients["dx"][1][2])
print("gradients[\"dx\"].shape =", gradients["dx"].shape)
print("gradients[\"da0\"][2][3] =", gradients["da0"][2][3])
print("gradients[\"da0\"].shape =", gradients["da0"].shape)


gradients["dx"][1][2] = [-0.15028183 -0.34554547  0.02071758  0.01483317]
gradients["dx"].shape = (3, 10, 4)
gradients["da0"][2][3] = -0.17268893183890804
gradients["da0"].shape = (5, 10)
